{"tag": "info", "depth": 0, "time": 1603434338.3264325, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"D:\\python3.7\\lib\\site-packages\\airtest\\cli\\runner.py\", line 61, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"E:\\\u9ec4\u632f\u65ed\\\u8d39\u7528\u7ba1\u7406\u7cfb\u7edf\u81ea\u52a8\u5316\u6d4b\u8bd5\u7528\u4f8b\\air\\test07_advance_charge.air\\test07_advance_charge.py\", line 10, in <module>\n    driver = WebChrome()\n  File \"D:\\python3.7\\lib\\site-packages\\airtest_selenium\\proxy.py\", line 31, in __init__\n    service_log_path=service_log_path, desired_capabilities=desired_capabilities)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 81, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\python3.7\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\nselenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 78\n\n"}}
